### ISSUE TITLE
Caravan Trader Spawn Too Much

### ISSUE THREAD

**Issue by ardissaps** [ArshiaDPG/Llamarama#39] opened 2022-07-31 08:43 UTC
My villlage is invaded by bunch of Caravan Trader.

**Comment by 0xJoeMama** [comment] 2022-07-31 12:33
Duplicate of #34

**Closed as completed** 2022-07-31 12:54 UTC
Labels: bug, duplicate, fixed in next release

**Comment by ardissaps** [comment] 2022-07-31 14:25
@0xJoeMama will it get fixed? As both post are closed, but thx anyway, such good potential

**Comment by 0xJoeMama** [comment] 2022-07-31 14:26
The release with the fix is already out. However it is in 1.19.

**Comment by ardissaps** [comment] 2022-07-31 14:31
alright, maybe I'll use it after official 1.20 mc update came out, as there will be eventually 1.19.2, 1.19.3, 1.19.5 etc  (I do have 1.19 installatation, but barely playing it) :-D

**Comment by 0xicl33n** [comment] 2022-10-01 21:23
> The release with the fix is already out. However it is in 1.19.

No 1.18 backport??? Chat reports are bad for the future of the game and i, like many others, have no interest in touching 1.19.1+
