### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArshiaDPG/Llamarama#5] opened 2022-01-18 20:35 UTC
https://pastebin.com/LpwKSYGM

**Comment by 0xJoeMama** [comment] 2022-01-18 20:44
Has this happened multiple times?

**Comment by TheButterbrotMan** [comment] 2022-01-19 16:23
No

**Comment by 0xJoeMama** [comment] 2022-01-19 16:26
How did you get it to happen because I cannot seem to be able to reproduce it?

**Comment by TheButterbrotMan** [comment] 2022-01-19 16:29
I dont know to be honest, it seems happen random. None of my players, did anything related to your mod.

**Comment by 0xJoeMama** [comment] 2022-01-19 16:39
So the server just crashed one time?

**Comment by 0xJoeMama** [comment] 2022-01-19 16:39
And if yes, has it  launched since?

**Comment by 0xJoeMama** [comment] 2022-01-19 16:40
Finally, is there a mod in your modpack, that adds any weird enchantment?

**Comment by 0xJoeMama** [comment] 2022-01-19 16:44
Also, I can tell you that I have identified the issue. However it doesn't seem to be caused by Llamarama, rather by an interaction between Llamarama and some other mod. That's why I've asked the questions above.

**Comment by TheButterbrotMan** [comment] 2022-01-19 16:56
> So the server just crashed one time?

Yes.

> And if yes, has it launched since?

Yes.



> Finally, is there a mod in your modpack, that adds any weird enchantment?

A lot. Some examples are Gobber, or Fabric Enchantments.

**Comment by TheButterbrotMan** [comment] 2022-01-19 16:56
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by 0xJoeMama** [comment] 2022-01-19 17:35
> > And if yes, has it launched since?
> 
> Yes.

Okay so this means the crash wasn't a hard one. However, it also means it's gonna be hard to find the mod that causes the problem. I am gonna go all out and say this: Llamarama is definitely not the mod causing the issue. I will implement a hard-coded fix however, just in case there is another mod that behaves this way. Thank you for your report.

**Comment by 0xJoeMama** [comment] 2022-01-20 17:45
`79b1907` should contain the fix for this. It will be released along with other bugfixes in 1.5.2. If you could wait until then, we would really appreciate it.

**Closed as completed** 2022-01-27 15:00 UTC
Labels: fixed in next release, mod-interop-issue
