### ISSUE TITLE
Mossy Llama griefing

### ISSUE THREAD

**Issue by TheMightyMcGrew** [ArshiaDPG/Llamarama#31] opened 2022-05-16 11:53 UTC
**Describe the bug**
AMossy Llamas wild and trader-owned both bypass flan claiming griefprevention

**To Reproduce**
Install flan claim mod, install llamarama, claim an area and mark it protected through flans menu, spawn mossy llama, wait a few secounds.

**Expected behavior**
I expected mossy llamas to not be able to change player owned claimed areas that are marked to prevent griefing/block changes.

**Screenshots**
![image_2022-05-16_145252050](https://user-images.githubusercontent.com/16889713/168586796-1500b569-0548-4a4c-b18f-ae70c67c1b05.png)

**Game Instance Information:**
Minecraft 1.18.1 Fabric

**Comment by 0xJoeMama** [comment] 2022-05-16 12:05
This is a really interesting bug. This is probably caused because of our using the default moss growth caused by bone meal. However I will have to look into flan claim, to see how it prevents building/modifying claimed terrain. Also it's my exams season so the fix will probably take a while to come out. However, I do thank you for your report/support!

**Comment by 0xJoeMama** [comment] 2022-05-16 12:10
Also are you sure that the ones spawned with traders also have this behavior? This issue was supposed to be fixed. Try spawning a llama like this: `/summon llamarama:mossy_llama ~ ~ ~ {Deadly:0b}`

**Comment by TheMightyMcGrew** [comment] 2022-05-16 13:26
> Also are you sure that the ones spawned with traders also have this behavior? This issue was supposed to be fixed. Try spawning a llama like this: `/summon llamarama:mossy_llama ~ ~ ~ {Deadly:0b}`

Tried this command with the same results, I believe this may be due to caravan changing wandering traders. We did however notice one spawn with a couple mossy llamas and they did continue to grief the area. In any case naturally spawned llamas and summoned still causing this issue. I tried to show that I used your command there but its only saying i summoned a mossy llama so youll have to take my word for it
![image](https://user-images.githubusercontent.com/16889713/168602975-7cb7737c-eb9e-4a9c-8a47-53e419ddbafe.png)

**Comment by TheMightyMcGrew** [comment] 2022-05-18 15:16
I have a temp fix for this now, which is just a command block running constantly to kill any mossy llama that spawns

**Comment by 0xJoeMama** [comment] 2022-05-19 16:08
I fixed the deadly issue. However the claiming issue, I will need to look into deeper.

**Comment by 0xJoeMama** [comment] 2022-05-22 09:46
@TheMightyMcGrew do you have any developer experience? If yes I would like to ask you a favor. Could you compile the Jar of the bugfixes/1.7.1 branch and check whether that fixes your issue or not?

**Comment by TheMightyMcGrew** [comment] 2022-05-22 10:52
> @TheMightyMcGrew do you have any developer experience? If yes I would like to ask you a favor. Could you compile the Jar of the bugfixes/1.7.1 branch and check whether that fixes your issue or not?

I dont have any experience but am more than willing to learn. AFAIK compiling is the easy part right? I should be able to hash that out. In the meantime however if you see this response and decide you can throw me a quick 1. 2. 3. on how to do that please do.

**Comment by 0xJoeMama** [comment] 2022-06-11 12:00
So I am finally done with exams and have some time to spend on this. However the whole claiming problem, doesn't seem to be something I can fix on our side. Most likely this is caused by the mod that you use to manage claims. **I only use vanilla methods to implement the desired behavior.** Theoretically speaking I should not have to handle these specific cases because **our mod isn't designed specifically with intend to work with your claiming mod or any claiming mod for that matter.**

Keep in mind I am not turning down your issue or refusing to work on it. There is just nothing I can do to prevent this behavior from occurring, considering claiming isn't vanilla behavior. I suggest you try newer versions of your claiming mod or opening an issue on their page. You could also reference this issue for further information.

**Comment by 0xJoeMama** [comment] 2022-06-11 12:51
#35 fixes the first half of this issue. I'll think about it a bit more and I might close this since I cannot think of anything to do for the second half.

**Closed as completed** 2022-07-31 12:54 UTC
Labels: bug, fixed in next release, partially-fixed
