### ISSUE TITLE
Causes crash on start up

### ISSUE THREAD

**Issue by mj717** [ArshiaDPG/Llamarama#2] opened 2021-06-06 21:50 UTC
I downloaded the 1.3.3 version of this mod, but it's crashing my game on startup.

EDIT: The crash seems to come from a mod conflict between this mod and the [Charm](https://www.curseforge.com/minecraft/mc-mods/charm) mod. Removing one or the other lets me run my game, but when I try to play with both mods the game crashes.

**Comment by mj717** [comment] 2021-06-06 22:36
I wasn't sure if this mod changed Wandering Trader behavior, but I knew that Charm does, so I disabled Charm's edits to Wandering Trader behavior in the mod's config file. That didn't have any effect on the apparent conflict between the two mods.

**Comment by 0xJoeMama** [comment] 2021-06-07 10:51
Could you send a crash-log?

**Comment by 0xJoeMama** [comment] 2021-06-07 10:52
You should use a paste website, don't just send it here. Make a paste and then send a link to it.

**Comment by 0xJoeMama** [comment] 2021-06-07 10:53
> I wasn't sure if this mod changed Wandering Trader behavior, but I knew that Charm does, so I disabled Charm's edits to Wandering Trader behavior in the mod's config file. That didn't have any effect on the apparent conflict between the two mods.

Also I don't see what the issue is currently. However the crashlog is gonna help.

**Comment by mj717** [comment] 2021-06-07 22:14
There was no crash report generated, but there was a log. I've never pasted/linked a report or log like this before, so please let me know if I did something wrong...

Link to log when both Llamarama and Charm are in mods folder and game crashes:
https://jpst.it/2wW2I

I'm not sure if this is useful but I also ran the game with just Charm and with just Llamarama (where the game does load) and made links for those too:
https://jpst.it/2wW3i
https://jpst.it/2wW3M

**Comment by mj717** [comment] 2021-06-07 22:30
There's no crash report, unfortunately, the game just tells me an unexpected error has occurred and gives me exit code 0. However, there was a log generated (please let me know if I did this wrong, I've never pasted/linked a log or report before).

This is the log when I just have Llamarama, Charm and the Fabric API: https://jpst.it/2wW4N
This is the log when I have Llamarama, Charm and all the other mods that I typically use: https://jpst.it/2wW2I

**Comment by 0xJoeMama** [comment] 2021-06-08 14:17
Hm... So I don't know why but for some reason the paste for me stops at "I used the json to destroy the json". Is that the case for you as well?

**Comment by 0xJoeMama** [comment] 2021-06-08 14:18
Also how did you reach the conclusion that llamarama and charm interacting, is what is causing this issue?

**Comment by mj717** [comment] 2021-06-08 14:32
Yes, that is what the log looks like. The log stops there, as the game loader crashed, giving me exit code 0, I think meaning it couldn't load the game.

> Also how did you reach the conclusion that llamarama and charm interacting, is what is causing this issue?

To try to figure out what the conflict was, I started removing and re-adding in the mods I use in batches. I took out every mod except the APIs and Libraries, ran the game with just those and Llamarama and the game worked fine. Then I started adding mods back in 5 at a time, alphabetically. I have about 70 mods, so it was great luck that Charm is close to the start of the alphabet. When the game crashed with those first 5 mods added, I removed them one by one until I found that the game crashed with just Charm and Llamarama (and the APIs). Then I ran my game with Llamarama and all of my mods except Charm, and the game did not crash. 

So, all of my other mods appear to work fine with Llamarama. But adding Charm in crashes the game.

**Comment by 0xJoeMama** [comment] 2021-06-08 19:03
So taking a look at the code Charm has, I have found some things that may be causing this conflict. Thank you, for your report. I'll take a look at what I can do.

**Comment by mj717** [comment] 2021-06-08 20:43
> So taking a look at the code Charm has, I have found some things that may be causing this conflict. Thank you, for your report. I'll take a look at what I can do.

Sounds good! Thanks for looking into this. Your mod is super great and I would love to use it.

**Comment by 0xJoeMama** [comment] 2021-06-09 10:26
The issue has been identified and fixed. Again thank you for your report. I will close this issue when a new version comes out.

**Closed as completed** 2021-06-09 10:31 UTC
Labels: bug, fixed in next release
