### ISSUE TITLE
[1.18.1] Lamas spawn too frequently

### ISSUE THREAD

**Issue by Joulanh** [ArshiaDPG/Llamarama#6] opened 2022-01-20 00:19 UTC
Last version for 1.18.1

Lamas of all sorts have basically no spawn restriction and spawn way too frequent. I have at least 20 lamas of all sorts in my base and i saw some in the desert and even on the main end iland :D
Which brings me to another point that the new vairant that spawns moss should maybe be a little more restricted as to where they can turn blocks into moss. It might only be so apperent to me since they basically spawn every 30 blocks in my base at the moment, but while the abillity is pretty cool it also partially griefes your base, which can be annoying at times.

**Comment by Joulanh** [comment] 2022-01-20 01:25
![2022-01-20_02 13 43](https://user-images.githubusercontent.com/80494384/150245332-2634b15a-7797-49d0-bc6d-d2d722cfaeda.png)

**Comment by Joulanh** [comment] 2022-01-20 01:26
Possible solutions might be:
-> only allowing blocks under the lama to be changed
-> reduce the frequency 
-> only allow gras to be changed

**Comment by 0xJoeMama** [comment] 2022-01-20 16:34
> Last version for 1.18.1
> 
> Lamas of all sorts have basically no spawn restriction and spawn way too frequent. I have at least 20 lamas of all sorts in my base and i saw some in the desert and even on the main end iland :D Which brings me to another point that the new vairant that spawns moss should maybe be a little more restricted as to where they can turn blocks into moss. It might only be so apperent to me since they basically spawn every 30 blocks in my base at the moment, but while the abillity is pretty cool it also partially griefes your base, which can be annoying at times.

Hello. Thank you for your report.

Firstly, regarding the issue with way to many blocks being changed by mossy llamas: the only blocks that change are the ones under the `#minecraft:moss_replacable` tag. The frequency, in that literally any block around them is changed is intentional. The llama can change blocks in a 5x2x5 centered around the block it's standing on. In other words, in can only change a 5x5 around the block its standing on and the ones directly above them. If you get blocks other than those in the aforementioned tag, make sure to tell us. However, if the issue is case specific, we cannot do anything about it.

Secondly, regarding spawning: There are two ways for the llamas of our mod to spawn. One of them is from caravan traders and the other one is natural spawning.

*Woolly llamas spawn in mountains much like regular llamas.
*Bumble llamas should only spawn in flower forests and nowhere else by default.
*Mossy llamas should only spawn in Lush caves and nowhere else by default.

Could you send the biome of your base as well as a picture of all the llamas that have spawned there? If you could we would highly appreciate you also send a top to bottom view(aerial) or your base.

Thank you again for the report.

**Comment by 0xJoeMama** [comment] 2022-01-20 17:36
> ![2022-01-20_02 13 43](https://user-images.githubusercontent.com/80494384/150245332-2634b15a-7797-49d0-bc6d-d2d722cfaeda.png)

Also this screenshot doesn't provide any information relevant to the problem, other than the fact that mossy llamas can replace stone.

**Comment by Joulanh** [comment] 2022-01-20 22:42
If mossy lamas should only spawn in lush caves then the mechanic makes total sense and is not too intrusive. The problem is our whole base is full with naturally spawned lama variants, wooly, bumble and mossy lamas which leads to a lot of "griefed" areas. 

The biomes are sparce jungle and a modded terralith biome calles temperate highlands. Maybe the spawning got messed up because of the custom terrain generation. 

My point with the screenshot was that the lama spawned there and was not led by a player, so there was no chance to prevent the conversion and this is only one of many places. I should have explained that better sry.


The lowest point where lamas are spawning was down at the bottom in front of the wheat fields. Biome: Sparce Jungle Height: 70
The lamas might have wandered there from the nearby biome im not sure.
The highest point where lamas are spawning is up at the castle at around height 170. Biome is temperate highlands from terralith.  

All variants have been seen at all altitudes and in about two days playing I had around 20 - 30 lamas spawning with half of them being Bumble and Mossy variants. 
I also saw lamas spawning in the desert. I'm not sure if this has something to do with it but almost always there were 3-4 lamas  spawning with 2 wooly or normal lamas 1 mossy lama and 1 bumble lama so it might be related to  pack spawning? thats just a wild guess tho.

If you want to i could test if i can recreate the spawning issues with only Llamarama installed :)



![2022-01-20_22 44 03](https://user-images.githubusercontent.com/80494384/150428066-13399e21-626c-45e1-918d-85b982743182.png)
![2022-01-20_22 44 23](https://user-images.githubusercontent.com/80494384/150428087-f43ab029-0a99-44b6-8361-668e9fc2687d.png)

**Comment by 0xJoeMama** [comment] 2022-01-21 09:47
I assume that since you aren't in any affected biomes, the issue is cause by caravan trader spawning. I'll look into that and let you know if I find something.

**Comment by 0xJoeMama** [comment] 2022-01-21 09:48
>If you want to i could test if i can recreate the spawning issues with only Llamarama installed :)

I was gonna try that, but it would really help if you also did.

**Comment by 0xJoeMama** [comment] 2022-01-23 19:30
> If you want to i could test if i can recreate the spawning issues with only Llamarama installed :)

Have you tried doing that? Because I've done a lot of tests and I never got that behavior.

**Comment by 0xJoeMama** [comment] 2022-01-23 19:31
At least I made some changes to the Caravan Trader spawning, so I hope those fix your issues.

**Comment by Joulanh** [comment] 2022-01-24 10:49
i tested for a bit but im a little bit busy with exams at the moment so i couldn't do much and also didnt find anything in vanilla. If the issue still prevails after the update and I have more time again ill check for the mod that causes the issue, but it will probably take a month or so till i have the time.

**Comment by 0xJoeMama** [comment] 2022-01-25 06:19
I am going to make a release but I'll keep this issue open, since I don't think it's fixed.

**Comment by 0xJoeMama** [comment] 2022-01-27 15:01
I am leaving this open just in case.

**Comment by TheButterbrotMan** [comment] 2022-01-30 02:20
They still spawning in massive frequencies

**Comment by 0xJoeMama** [comment] 2022-01-30 13:04
> They still spawning in massive frequencies

You need to use the latest version which I wasnt able to release to curseforge yesterday because the website was experiencing issues. Try today's release

**Comment by 0xJoeMama** [comment] 2022-01-30 17:51
The latest version of the mod is now release on curseforge.

**Comment by Joulanh** [comment] 2022-02-09 16:58
since the latest version i havent noticed the wrong lamas spawning on the surface anymore, but there seems to be no limit to mossy lamas spawning in lush caves. 

We were wondering why the server is so laggy an it turned out that about 1300 mossy lamas were alive in a lush cave that was only loaded by one player.  

After we killed all the lamas and and did some testing we figuered out that everey time the chunks with lush caves were loaded about 70 new mossy lamas were spawning but not despawning when leaveing the area, which adds up over time.
![2022-02-09_17 45 32](https://user-images.githubusercontent.com/80494384/153250579-39cb4c7b-40ef-4f39-9b3b-073f2f6a3da7.png)

**Comment by 0xJoeMama** [comment] 2022-02-09 17:49
> since the latest version i havent noticed the wrong lamas spawning on the surface anymore, but there seems to be no limit to mossy lamas spawning in lush caves.


I think you might be using the wrong `latest` version. Make sure you are on `1.5.3` and no other version because the reason that version was released was because of that very bug.

**Comment by Joulanh** [comment] 2022-02-09 18:02
oh wow im sorry and blind :D

**Comment by 0xJoeMama** [comment] 2022-02-09 18:15
> oh wow im sorry and blind :D

Don't worry we are humans after all!

**Comment by 0xJoeMama** [comment] 2022-02-09 18:15
Mistakes happen lol

**Comment by 0xJoeMama** [comment] 2022-02-28 13:38
I think most of these issues have also been resolved. I am going to close this issue as well, since no one has taken further notice of any issues. Thanks for your assistance in fixing issues in the mod. Thank you for your support!

**Closed as completed by 0xJoeMama** 2022-02-28 13:38 UTC
Labels: help wanted, fixed in next release, needs-more-info
